version: 2
jobs:
    build:
        docker:
          - image: cimg/rust:1.67.1
        steps:
#             - working_directory: ~/work
            - checkout
            - run:
                command: |
                  cd rs-netcat
                  cargo build
    test:
        docker:
          - image: cimg/rust:1.67.1
        steps:
            - working_directory: ~/work
            - checkout
            - run:
                command: |
                  cargo test
workflows:
  version: 2
  all:
    jobs:
        - build
        - test:
            requires:
            - build
